name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release

    - shell: bash
      run: |
        mv target/release/rustlens rustlens
        chmod 777 rustlens
        tar cpfz rustlens_linux_x86_64.tar.gz rustlens

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: rustlens_linux_x86_64.tar.gz
