name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release

    - shell: bash
      run: |
        mv target/release/rustlens rustlens
        chmod 777 rustlens
        tar cpfz rustlens_linux_x86_64.tar.gz rustlens

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: rustlens_linux_x86_64.tar.gz

  windows_build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release

    - name: Prepare artifact
      shell: pwsh
      run: |
        Move-Item target/release/rustlens.exe rustlens.exe
        Compress-Archive -Path rustlens.exe -DestinationPath rustlens_windows_x86_64.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: rustlens_windows_x86_64.zip

  macos_build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release

    - shell: bash
      run: |
        mv target/release/rustlens rustlens
        chmod 777 rustlens
        tar cpfz rustlens_macos_x86_64.tar.gz rustlens

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: rustlens_macos_x86_64.tar.gz
